### ISSUE TITLE
Make june work with windows

### ISSUE THREAD

**Issue by bartanderson** [mezbaul-h/june#7]
Maybe add a section for windows and specify pip install pyaudio rather than portaudio19.
I was able to get it to work but wasn't able to get it to work with pyinstaller.
I was able to get it to run using python -m june_va

**Comment by mezbaul-h** [comment]
`PyAudio` is already part of the package requirements, so there's no need to explicitly install it. However, I agree that I should add a note clarifying that the `portaudio` headers are only for Debian-based systems.

Regarding the issue you encountered with installation, I believe the problem might be related to the `coqui-tts` package. It requires `Microsoft Visual C++ 14.0` or greater (which can be downloaded here: https://visualstudio.microsoft.com/visual-cpp-build-tools/). I'll make sure to mention this in the installation section to help others avoid the same issue.

It seems that because `coqui-tts` fails to install properly, the program ends up only partially installed. That's why you can execute it with `python -m june_va` but not with `june-va` directly.

I'd really appreciate if you could share your command line logs showing the installation errors. This would help me understand the issue better and potentially improve the installation process for Windows users.
