### ISSUE TITLE
Mac OS - Doesn't pick up sound

### ISSUE THREAD

**Issue by gshipley** [mezbaul-h/june#9]
 gshipley  …/june   master   v3.11.9  
 june-va
[system]> Listening for sound...

Just hangs. Verified audio is working with other programs and recordings.

tried with both cpu and mps devices for torch

**Comment by mezbaul-h** [comment]
Are you using an external microphone or the built-in one?

You can try decreasing the `THRESHOLD` to something like 500 or lower:
https://github.com/mezbaul-h/june/blob/96f0d42e95e24681c936c04de18485da7b122755/june_va/audio.py#L32
Remember to reinstall the app after changing this value.

**Comment by kellerkind84** [comment]
Hi there, I think your first idea was correct. Since you don't specifically pick input devices, it will use one by default. According to the docs, that would be the system wide microphone, but when I tested it that does not seem to work as advertized...

So I changed this:

```
self.input_stream = self.pa.open(
            channels=1,
            format=pyaudio.paInt16,
            frames_per_buffer=self.CHUNK,
            input=True,
            rate=self.RATE,
            input_device_index=4,
        )
```

See the input_device_index... I obviously hard-coded here, but you could use something like this:

```
        print("Available audio input devices:")
        info = self.p.get_host_api_info_by_index(0)
        numdevices = info.get('deviceCount')
        for i in range(0, numdevices):
            if (self.p.get_device_info_by_host_api_device_index(0, i).get('maxInputChannels')) > 0:
                print(f"Input Device id {i} - {self.p.get_device_info_by_host_api_device_index(0, i).get('name')}")

        device_index = int(input("Enter the device id of the microphone you want to use: "))
```
